Console.WriteLine("Yeah, yeah, yeah");
Console.WriteLine("Maquinário insano, eu tô bongando");
Console.WriteLine("Dentro do Camaro branco, eu vou passar voando");
Console.WriteLine("Tô de mala pronta");
Console.WriteLine("E eu só volto lá depois da última ponta");
Console.WriteLine("");
Console.WriteLine("Freestyle Lugar Distante");
Console.WriteLine("Vai, aperta o REC e taca fogo na blunt");
Console.WriteLine("Deixa o som bater na porra do alto-falante");
Console.WriteLine("E o seus problemas vão ser irrelevantes");
Console.WriteLine("(Tem que ser capaz!)");
Console.WriteLine("");
Console.WriteLine("Me desliguei pra ir pr'um lugar distante");
Console.WriteLine("Longe dеssa negatividade que еxpande");
Console.WriteLine("Ver o Sol descer na vegetação do mangue");
Console.WriteLine("Viver a vida no estilo me lambe");
Console.WriteLine("(Ai já é querer demais)");
Console.WriteLine("");
Console.WriteLine("Não é nada pra nós");
Console.WriteLine("Cê quer hash? Tem!");
Console.WriteLine("Extrato? Tem!");
Console.WriteLine("Cogu tem também? Tem!");
Console.WriteLine("O que te der vontade, é só tu me ligar");
Console.WriteLine("(Basta você me ligar)");
Console.WriteLine("");
Console.WriteLine("Tiqui-tim, dinheiro não é mais preocupação pra nós");
Console.WriteLine("Um sonho num estante");
Console.WriteLine("Freestyle de um lugar distante");
Console.WriteLine("Pra deixar tua cabeça dando um nó-o-oh");
Console.WriteLine("Pra deixar tua cabeça dando um nó-oh");
Console.WriteLine("Deixar tua cabeça dando um nó-o-oh");
Console.WriteLine("Deixar tua cabeça dando um nó-o-oh");
Console.WriteLine("Ye-é-ye-é-yeah");